name: Deploy DatalandMCP server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY  }}

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy DatalandMCP service
        run: |
          bash deployment/deployment.sh \
          --host ${{ secrets.EC2_HOST_QALAB }} \
          --user ${{ secrets.EC2_USER }} \
          --api-key ${{ secrets.DATALAND_API_KEY }}
